apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: app_code_image
    newName: ghcr.io/${{ values.owner }}/${{ values.app_code_repo_name }}
    newTag: ${{ values.app_code_initial_hash }}

resources:
- deployment.yaml
- ingress.yaml
- service.yaml