apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{values.application_name}}
    backstage.io/kubernetes-id: ${{values.application_name}}
  name: ${{values.application_name}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: ${{values.application_name}}
  type: ClusterIP